name:                simpl-lang
version:             0.1.0.0
github:              "Technius/simpl-lang"
license:             Apache-2.0
author:              "Bryan Tan"
maintainer:          "Bryan Tan"
copyright:           "Bryan Tan (Technius) 2018"

extra-source-files:
- README.md
- ChangeLog.md
- runtime/**/*.c
- runtime/Makefile

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Technius/simpl-lang#readme>

data-files: runtime/**/*.ll

custom-setup:
  dependencies:
  - Cabal >= 2.2.0.0 && < 3
  - base >= 4.7 && < 5

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec >= 6.5.0 && < 7
- parser-combinators
- recursion-schemes
- deriving-compat
- llvm-hs-pure >= 7 && < 8
- llvm-hs >= 7 && < 8
- prettyprinter
- unification-fd
- mtl
- containers
- bytestring
- optparse-applicative
- safe-exceptions

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  simplc:
    source-dirs: compiler
    main: Simplc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simpl-lang
  simpl-repl:
    source-dirs: repl
    main: SimplRepl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simpl-lang

tests:
  simpl-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simpl-lang
