# Build steps adapted from
# https://circleci.com/docs/2.0/language-haskell/ (Feb 19 2019)

version: 2
jobs:
  build:
    docker:
      - image: technius/simpl-circleci:0.0.3

    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          key: stack-cache-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Setup GHC
          command: stack setup
      - run:
          name: Compile
          command: stack build
      - run:
          name: Run unit tests
          command: stack test
      - save_cache:
          name: Cache dependencies
          key: stack-cache-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - "~/.stack"
            - ".stack-work"
